# Generated by Django 5.2.7 on 2026-04-10 21:20

import django.utils.timezone
import exchange.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wallet', models.CharField(choices=[('waafi', 'Waafi Mobile Money'), ('cac', 'CAC International Bank'), ('dmoney', 'D-Money'), ('saba', 'Saba African Bank')], max_length=20)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('screenshot', models.ImageField(upload_to=exchange.models.screenshot_upload_path)),
                ('moneygo_wallet', models.CharField(max_length=100, verbose_name='MoneyGo Wallet ID')),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Request',
                'verbose_name_plural': 'Exchange Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
